### PR TITLE
Spanish Survey for 2023

### PR DESCRIPTION
**Pull request by ViralBShah**
@Roger-luo How should we do this? Should I merge this, or should the spanish language person update this PR and we get it to pass CI and then merge when fully ready?

### CODE REVIEW

**Comment by ViralBShah** [comment]
Merging now so that we can work on a branch (instead of a fork).

**Comment by ViralBShah** [comment]
Apologies that this was not squashed. :-(

**Comment by Roger-luo** [comment]
np, I think you can just go ahead as long as someone confirms things are correct - we don't have any automation on checking translation quality so if it's only changing the TOML files you don't need to wait for CI at all - they don't check the TOML files.

**Comment by ViralBShah** [comment]
Thanks.

**Pull request merged**
